import React from 'react'

export default function DigitalAuditWidget() {
    return (
        <div>
            <script id="__v_snapshot_widget" src="https://www.cdnstyles.com/static/snapshot_widget/v1/snapshot.widget.js" data="eyJhcGlLZXkiOiJlNmU2MmE1OS1iYWE3LTQzNmEtYjdmMy1lMDQwOGM0Mzc2YzkiLCJiYWNrZ3JvdW5kQ29sb3IiOiIjRkZGRkZGIiwiYm9yZGVyQ29sb3IiOiIjRkZGRkZGIiwiYm9yZGVyUmFkaXVzIjoxNSwiYnV0dG9uQ29sb3IiOiIjMGNhOWQ2IiwiYnV0dG9uRm9udENvbG9yIjoiI0ZGRkZGRiIsImJ1dHRvblRleHQiOiJTdGFydCIsImNvbmZpcm1hdGlvbkJvZHlUZXh0IjoiT25jZSBpdCdzIHJlYWR5LCB3ZSdsbCBzZW5kIHlvdXIgcmVwb3J0IHRvIHRoZSBlbWFpbCBhZGRyZXNzIHlvdSBoYXZlIHByb3ZpZGVkLiIsImNvbmZpcm1hdGlvblRpdGxlVGV4dCI6IldlJ3JlIGdlbmVyYXRpbmcgeW91ciByZXBvcnQhIiwiY29uc2VudEluZm9ybWF0aW9uVGV4dCI6IiIsImRhdGFQcm90ZWN0aW9uUG9saWN5VGV4dCI6IiIsImRyb3BTaGFkb3ciOnRydWUsImVtYWlsTm90aWZpY2F0aW9uQWdyZWVtZW50VGV4dCI6IiIsInBhcnRuZXJJZCI6IlRHR1AiLCJwcmltYXJ5Rm9udENvbG9yIjoiIzIyMjIyMiIsInNlY29uZGFyeUZvbnRDb2xvciI6IiM5QjlCOUIiLCJ0aXRsZVRleHQiOiJSZXZpZXcgTXkgT25saW5lIFByZXNlbmNlIiwidXJsIjoiaHR0cHM6Ly9zbmFwc2hvdC13aWRnZXQtcHJvZC5hcGlnYXRld2F5LmNvLyIsIndpZGdldElkIjoiU05BUFNIT1QtV0lER0VULTMwOGI1Y2UwLTY3OWItNGUxMy1hNmY2LWYxYTFjYTQyZmFiNiIsIndpZHRoIjowfQ==" defer></script>
        </div>

    )
}
